on:
  push:
    branches:
      - fake-test
    tags:
      - v[0-9].[0-9].[0-9]
  pull_request:
    branches:
      - fake-test

jobs:

  # 1) Run all unit tests
  run-tests:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/run-tests.yml

  # 2) Deploy to the aws nonprod css account if the test branch is pushed to or is the target of a pull request.
  deploy-test:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/fake-test' || github.base_ref == 'refs/heads/fake-test' || false }}
    needs: run-tests
    uses: ./.github/workflows/deploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.CSS_NONPROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CSS_NONPROD_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

  # else...

  # 2a) Require that if the trigger is due to a tag being pushed, that the tag must also apply to a commit in the main branch 
  check-prod:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: run-tests
    steps:
      - run: echo '${{ toJSON(github) }}'
      - run: |
          if [ -z "$(git tag --merged fake-prod | grep '^${{ github.ref }}$' 2> /dev/null)" ] ; then
            echo 'Prod release tag applied, but not reachable from fake-main branch!'
            exit 1
          else
            exit 0
          fi

  # 2b) Deploy to the aws prod css account.
  deploy-prod:
    runs-on: ubuntu-latest
    needs: check-prod
    uses: ./.github/workflows/deploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.CSS_PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CSS_PROD_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1



